stages:
  - build
  - dockerize
  - upload

variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_IMAGE_NAME: "eureka-server"
  AWS_S3_BUCKET: "backend-challenge"
  AWS_REGION: "us-east-2"


build_eureka_service:
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - echo "Compilando el microservicio eureka-server..."
    - cd eureka-server
    - mvn clean install $MAVEN_CLI_OPTS
    - ls -l target/
    - ls -l

  artifacts:
    paths:
      - eureka-server/target/*.jar

dockerize_eureka_service:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Preparando el archivo JAR para el build Docker..."
    - mv eureka-server/target/eureka-server.jar eureka-server/ # Copia el JAR al nivel del Dockerfile
    - echo "Construyendo la imagen Docker de eureka-server..."
    - docker build -t $DOCKER_IMAGE_NAME:eureka-server-latest -f eureka-server/Dockerfile eureka-server/
    - docker save $DOCKER_IMAGE_NAME:eureka-server-latest > eureka-server.tar
  artifacts:
    paths:
      - eureka-server.tar


upload_eureka_server_to_s3:
  stage: upload
  image: amazonlinux:2
  before_script:
    - yum install -y aws-cli
  script:
    - ls -l
    - echo "Configurando AWS CLI..."
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - echo "Verificando configuración de AWS CLI..."
    - aws s3 ls
    - echo "Subiendo imagen Docker a S3..."
    - aws s3 cp eureka-server.tar s3://$AWS_S3_BUCKET/project/eureka-server.tar --region $AWS_REGION