stages:
  - build
  - dockerize
  - upload

include:
  - local: '/user-service/.gitlab-ci.yml'
  - local: '/account-service/.gitlab-ci.yml'
  - local: '/card-service/.gitlab-ci.yml'
  - local: '/transaction-service/.gitlab-ci.yml'

workflow:
  rules:
    - changes:
        - user-service/**
        - account-service/**
        - card-service/**
        - transaction-service/**
