stages:
  - build_eureka
  - dockerize_eureka
  - upload_eureka
  - build_user
  - dockerize_user
  - upload_user
  - build_account
  - dockerize_account
  - upload_account
  - build_config
  - dockerize_config
  - upload_config
  - build_gateway
  - dockerize_gateway
  - upload_gateway
  - build_card
  - dockerize_card
  - upload_card
  - build_transaction
  - dockerize_transaction
  - upload_transaction

.build_template: &build_template
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - echo "Compilando el microservicio $SERVICE_NAME..."
    - cd $SERVICE_NAME
    - mvn clean install $MAVEN_CLI_OPTS
  artifacts:
    paths:
      - $SERVICE_NAME/target/*.jar

build_config_server:
  <<: *build_template
  variables:
    SERVICE_NAME: config-server

build_gateway:
  <<: *build_template
  variables:
    SERVICE_NAME: gateway

build_card_service:
  <<: *build_template
  variables:
    SERVICE_NAME: card-service

build_transaction_service:
  <<: *build_template
  variables:
    SERVICE_NAME: transaction-service

.dockerize_template: &dockerize_template
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - mv $SERVICE_NAME/target/$SERVICE_NAME.jar $SERVICE_NAME/
    - docker build -t $DOCKER_IMAGE_NAME:$SERVICE_NAME-latest -f $SERVICE_NAME/Dockerfile $SERVICE_NAME/
    - docker save $DOCKER_IMAGE_NAME:$SERVICE_NAME-latest > $SERVICE_NAME.tar
  artifacts:
    paths:
      - $SERVICE_NAME.tar

dockerize_config_server:
  <<: *dockerize_template
  variables:
    SERVICE_NAME: config-server
    DOCKER_IMAGE_NAME: config-server

dockerize_gateway:
  <<: *dockerize_template
  variables:
    SERVICE_NAME: gateway
    DOCKER_IMAGE_NAME: gateway

dockerize_card_service:
  <<: *dockerize_template
  variables:
    SERVICE_NAME: card-service
    DOCKER_IMAGE_NAME: card-service

dockerize_transaction_service:
  <<: *dockerize_template
  variables:
    SERVICE_NAME: transaction-service
    DOCKER_IMAGE_NAME: transaction-service

.upload_template: &upload_template
  stage: upload
  image: amazonlinux:2
  before_script:
    - yum install -y aws-cli
  script:
    - aws s3 cp $SERVICE_NAME.tar s3://$AWS_S3_BUCKET/project/$SERVICE_NAME.tar --region $AWS_REGION

upload_config_service_to_s3:
  <<: *upload_template
  variables:
    SERVICE_NAME: config-server

upload_gateway_to_s3:
  <<: *upload_template
  variables:
    SERVICE_NAME: gateway

upload_card_service_to_s3:
  <<: *upload_template
  variables:
    SERVICE_NAME: card-service

upload_transaction_service_to_s3:
  <<: *upload_template
  variables:
    SERVICE_NAME: transaction-service
