version: '1.0'

services:
  eureka-server:
    build: eureka-server/
    mem_limit: 512m
    ports:
      - 8761:8761
  config-server:
    build: config-server/
    mem_limit: 512m
    ports:
      - 8888:8888
    env_file:
      - .env
  user-service:
    build: user-service/
    mem_limit: 512m
    ports:
      - 8081:8080
    env_file:
      - .env
  account-service:
    build: account-service/
    mem_limit: 512m
    ports:
      - 8085:8080
    env_file:
      - .env
  transaction-service:
    build: transaction-service/
    mem_limit: 512m
    ports:
      - 8086:8080
    env_file:
      - .env
  card-service:
    build: card-service/
    mem_limit: 512m
    ports:
      - 8087:8080
    env_file:
      - .env
  gateway:
    build: gateway/
    mem_limit: 512m
    ports:
      - 8083:8083
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    mem_limit: 600m
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: ${KEYCLOAK_HOSTNAME_PORT:-8080}
      KC_HOSTNAME_STRICT_BACKCHANNEL: ${KC_HOSTNAME_STRICT_BACKCHANNEL:-"true"}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED:-"true"}
      KC_LOG_LEVEL: ${KC_LOG_LEVEL:-info}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command:
      [
        "start-dev",
        "--http-port",
        "8080",
        "--https-port",
        "7443",
        "--import-realm"
      ]






