server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://ecstatic_mendeleev:8080/realms/BackendChallenge
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**

        - id: card-service
          uri: lb://CARD-SERVICE
          predicates:
            - Path=/cards/**

