server:
  port: 8083
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/BackendChallenge
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: account-service
          uri: http://localhost:8085
          predicates:
            - Path=/accounts/**

        - id: transaction-service
          uri: http://localhost:8086
          predicates:
            - Path=/transactions/**

        - id: card-service
          uri: http://localhost:8087
          predicates:
            - Path=/cards/**

