stages:
  - build
  - dockerize
  - upload

variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_IMAGE_NAME: "transaction-service"
  AWS_S3_BUCKET: "backend-challenge"
  AWS_REGION: "us-east-2"


build_transaction_service:
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - echo "Compilando el microservicio transaction-service..."
    - cd transaction-service
    - mvn clean install $MAVEN_CLI_OPTS
    - ls -l target/
    - ls -l

  artifacts:
    paths:
      - transaction-service/target/*.jar

dockerize_transaction_service:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Preparando el archivo JAR para el build Docker..."
    - mv transaction-service/target/transaction-service.jar transaction-service/ # Copia el JAR al nivel del Dockerfile
    - echo "Construyendo la imagen Docker de transaction-service..."
    - docker build -t $DOCKER_IMAGE_NAME:transaction-service-latest -f transaction-service/Dockerfile transaction-service/
    - docker save $DOCKER_IMAGE_NAME:transaction-service-latest > transaction-service.tar
  artifacts:
    paths:
      - transaction-service.tar


upload_transaction_service_to_s3:
  stage: upload
  image: amazonlinux:2
  before_script:
    - yum install -y aws-cli
  script:
    - ls -l
    - echo "Configurando AWS CLI..."
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - echo "Verificando configuración de AWS CLI..."
    - aws s3 ls
    - echo "Subiendo imagen Docker a S3..."
    - aws s3 cp transaction-service.tar s3://$AWS_S3_BUCKET/project/transaction-service.tar --region $AWS_REGION