stages:
  - build
  - dockerize
  - upload

variables:
  MAVEN_CLI_OPTS: "-DskipTests"
  DOCKER_IMAGE_NAME: "user-service"
  AWS_S3_BUCKET: "backend-challenge"
  AWS_REGION: "us-east-2"


build_user_service:
  stage: build
  image: maven:3.8.1-openjdk-17
  script:
    - echo "Compilando el microservicio user-service..."
    - cd user-service
    - mvn clean package $MAVEN_CLI_OPTS
    - ls -l target/
    - ls -l

  artifacts:
    paths:
      - user-service/target/*.jar

dockerize_user_service:
  stage: dockerize
  image: docker:latest
  services:
    - docker:dind
  script:
    - echo "Preparando el archivo JAR para el build Docker..."
    - mv user-service/target/user-service.jar user-service/ # Copia el JAR al nivel del Dockerfile
    - echo "Construyendo la imagen Docker de user-service..."
    - docker build -t $DOCKER_IMAGE_NAME:user-service-latest -f user-service/Dockerfile user-service/
    - docker save $DOCKER_IMAGE_NAME:user-service-latest > user-service.tar
  artifacts:
    paths:
      - user-service.tar


upload_user_service_to_s3:
  stage: upload
  image: amazonlinux:2
  before_script:
    - yum install -y aws-cli
  script:
    - ls -l
    - echo "Configurando AWS CLI..."
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_REGION
    - echo "Verificando configuración de AWS CLI..."
    - aws s3 ls
    - echo "Subiendo imagen Docker a S3..."
    - aws s3 cp user-service.tar s3://$AWS_S3_BUCKET/project/user-service.tar --region $AWS_REGION